export const RECEIVE_USERS = 'RECEIVE_USERS';
export const UPDATE_USER_QUESTIONS = 'UPDATE_USER_QUESTIONS';
export const UPDATE_USER_ANSWERS = 'UPDATE_USER_ANSWERS';
export const SET_AUTH_USER = 'SET_AUTH_USER';
export const RECEIVE_QUESTIONS = 'RECEIVE_QUESTIONS';
export const ADD_QUESTION = 'ADD_QUESTION';
export const VOTE_QUESTION = 'VOTE_QUESTION';
